import { Amatic_SC } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const inter = Amatic_SC({ subsets: ["hebrew"], display: "swap", style: "normal", weight: '700', stretch: "normal", variant: "normal", size: "100%", lineHeight: 1.5, text: "inherit", textTransform: "none", letterSpacing: "normal"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <div className="h-[100vh]">
          <Navigation />
          {children}
        </div>
      
        
        </body>
    </html>
  );
}
